### ISSUE TITLE
Having problems with modifying tikz-pgf content

### ISSUE THREAD

**Issue by youssefkaram** [jankapunkt/latexcv#10]
Hello jankapunkt!

CV looks amazing and very nice.

I am trying to use it for a sponsorship proposal but I'm having trouble with a couple of stuff.

- Trying to add a logo next to the title but it moves everything when I do
- Trying to add a number in the center of the pie chart
- Table is either too small or too big and out of bounds
- Trying to add text next to the fact bubble on the bottom of the page but it is being generated either too big or in  a very unorganized way
- How do I change the main colors?

I am not asking for you to do the work for me but please if you know how to fix any of these issues because I've really been struggling with this for two days.

Any help is appreciated!

Thank you!
[Sponsorship Proposal.zip](https://github.com/jankapunkt/latexcv/files/2358731/Sponsorship.Proposal.zip)

**Comment by jankapunkt** [comment]
Hello @youssefkaram 

the infographics cv has very carefully crafted and took ages to position elements by hand. Changing things can easily break the whole layout, which is why this template is considered to be very complex and time consuming (but rewarding in the end).

> Trying to add a logo next to the title but it moves everything when I do


> Trying to add a number in the center of the pie chart

Look at the fact bubble:

```
\parbox[c][3cm][c]{0.32\textwidth}{
    \begin{center}
        \factbubble{\huge{\textcolor{sectcol}{\textbf{M.Sc.}}}\\\small{\textcolor{sectcol}{\textbf{Digital Media}}}}{1}{maincol}{sectcol}{thirdcol}\\
        \textcolor{textcol}{as latest degree from}\\
        \textcolor{textcol}{\textbf{University of Bremen}}
    \end{center}
}
```

Which places the text inside it. The underlying techique to render the circle is similar to the one to render the pie chart. If you look into the code of the fact bubble you can get something out of it that can be placed into the pie chart.

> Table is either too small or too big and out of bounds

The template I added does not really has a table, which table are you referring to?

> Trying to add text next to the fact bubble on the bottom of the page but it is being generated either too big or in a very unorganized way

I can't fully compile your tex file so I can't say what's displayed.

> How do I change the main colors?

Look at the section , called `Color DEFINITIONS`, where the defaul color set is defined like so:

```
%main color
\definecolor{maincol}{RGB}{255,0,0} % pure red
```


I hope this helps a bit. If you think, that you have improved this template and like to share it, please leave a pull request.

**Comment by youssefkaram** [comment]
Hello again!

Sorry for the late reply. As soon as I finish working on it I'll upload it, that way there would be another template based on yours!

> I can't fully compile your tex file so I can't say what's displayed.

I attached the main file but uploaded it as a txt file instead due to github restrictions.

> The template I added does not really has a table, which table are you referring to?

I added a table below the bar chart

> Which places the text inside it. The underlying techique to render the circle is similar to the one to render the pie chart. If you look into the code of the fact bubble you can get something out of it that can be placed into the pie chart.

Couldn't really figure out how to add the text in the center of the piechart. I'm kinda of a beginner on LaTeX. Trying my best!

One last question. How can I add colors to the bar chart? You already have three colors assigned. Can't seem to figure out how to add colors to it.

Thank you!

[main.txt](https://github.com/jankapunkt/latexcv/files/2366651/main.txt)
