### ISSUE TITLE
Features / ideas for more CV templates / next version

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/latexcv#18]
So I am about to create some more CV templates and I'd like you to share some ideas, wishes, requirements and so on.

The only restriction is, that we won't copy / mime existing templates. However, inspirational input from existing templates (written or not written in LaTeX) is greatly appreciated.

**Comment by CsatiZoltan** [comment]
It would help me if you included a template tailored to scientific use: list of publications.

**Comment by jankapunkt** [comment]
Hi @CsatiZoltan thank you for the input. Basically you can modify any of the templates to add another section than "educaion" and "experience". But yeah, I could add another template that would focus more on scientific work, where layout is more structured to fit typical milestones of a scientific career path: Publications, Conferences, Institutes, Memberships etc. What do you think about that?

**Comment by CsatiZoltan** [comment]
That would be perfect, I didn't dare to ask it.  :)

This is how I imagine.
1. Header: name in larger font size, current position, title (e.g. PhD student, associate professor, etc.), address, institutional e-mail, phone number, optionally personal webpage, optionally a photo on the right as you did in the *Modern* template.
2. Education: the structuring in the *Classic* or the *Modern* templates are perfect I think.
3. Academic employment (optional; not useful for a freshly graduated person): title of the position, institution, time interval
4. Publications (optional, as some institutions require the publications separated from the CV): your own name in bold face to indicate whether you are the first author. I would further structure it as
    - books
    - journal papers
    - conference papers
    - book chapters
    - conference talks
    - publications under review
5. Awards (optional)
6. Teaching (optional)
7. Affiliations (optional): mainly relevant for experienced scientists and professors who are often members of organizations, committees, or are journal editors
8. Research interest (optional)
9. Technical skills: here I would add the option to insert the level of knowledge as it can be seen in the *Sidebar* theme (although I would change the stars to empty/filled circles as academia is more modest).

Additional comments:
- the default paper size could be A4 (tailored to me, as I am in Europe), with the possible extension to other sizes (not important for me)
- this template would specifically be crafted for use in academia
- as you could see, I wrote the word optional for some places. It could be implemented as environments, to keep the modular structure, suitable for PhD students to full professors. Similarly, one may not want to use all four kinds of publications listed in item 4, so macros could help here as well.
- the growing number of publications makes it impractical to embed them directly. I would use the `natbib`, or better, the `biblatex` package to fetch the publications from (an) external bib file(s). Biblatex can include multiple bibliographies within a single document, so that would fit well to the different categories (journal papers, copnference papers, ...).
- as opposed to business CVs, academic CVs can be longer due to the accumulating papers, memberships, etc.
- just as you did for the education section, the publication should also be ordered latest to oldest. I can help you in setting it in the bibliography, if you want.

**Comment by jankapunkt** [comment]
Thank you, this is a nice description and I will consider it for the new template. I would add you as reviewer, once the PR is opened.

**Comment by CsatiZoltan** [comment]
@jankapunkt Yes, perfect.

**Comment by olimanger** [comment]
Moin @jankapunkt , more than awesome artwork in the existing versions of your templates.
Using them, I came across the following hurdles/missing features:
1. a flexible number of sub-points in the \cv_event, most preferably with something like
`%----------------------------------------------------------------------------------------
%	 CV SUBEVENT
%----------------------------------------------------------------------------------------
% creates an infinite number of subentry-dots
\newcommand{\cvsubevent}[1]
{\begin{tabular*}{0.5\mpwidth}{p{\mpwidth}}\larrow{softcol}  #1 \checknextarg}
\newcommand{\checknextarg}{\@ifnextchar\bgroup{\gobblenextarg}{ \end{tabular*}}}
\newcommand{\gobblenextarg}[1]{\\[3pt] \larrow{softcol} #1\@ifnextchar\bgroup{\gobblenextarg}{ \end{tabular*}}}
`  
2. a good place for the date of birth, citizenship and a digitized signature?
3. solution for longer names (best would be a flexible solution
4. line wrapping in skills section (I q&d tweaked it with stackrel, but that's not so elegant)
