### ISSUE TITLE
How to remove footer from sidebar template

### ISSUE THREAD

**Issue by setegonz** [jankapunkt/latexcv#34]
Hi Jan, thanks for your wonderful work. I would like to know how I can remove the footer from the sidebar template. I commented on the code that generates the footer but then the white space at the end of the page is too big. How could I reduce that white space?

**Comment by jankapunkt** [comment]
Hi @setegonz which of the sidebar templates (left or right)?

**Comment by setegonz** [comment]
@jankapunkt right.

**Comment by jankapunkt** [comment]
Hey @setegonz sorry for the late reply, it is due to the minipages height being fixed. The main part and the sidebar are wrapped in minipage environments and their height is set to `0.95\textheight`, see these two lines:

https://github.com/jankapunkt/latexcv/blob/master/sidebar/main.tex#L311
https://github.com/jankapunkt/latexcv/blob/master/sidebar/main.tex#L421

You should be able to play with the height value to make the boxes fit to your needs.

**Comment by setegonz** [comment]
@jankapunkt Thank you very much for making this resource available!

**Comment by jankapunkt** [comment]
@setegonz did it help?

**Comment by jankapunkt** [comment]
@setegonz did it help?

**Comment by jankapunkt** [comment]
@setegonz friendly ping

**Comment by setegonz** [comment]
@jankapunkt It works! Thanks.
