### ISSUE TITLE
Multi-line CV event

### ISSUE THREAD

**Issue by sebastian-raubach** [jankapunkt/latexcv#8]
Great work on these latex templates! I'm really enjoying working with them.
I do have a minor issue with the modern template though:

Currently, when your "title" of a `\cvevent` (second parameter) is quite long it wraps to the next line, but the header section doesn't adjust.
I could get around this by modifying the `\vspace` between the header and the body, but would prefer a more generic solution.

Is there any way to move the body down if the header has wrapped text?

**Comment by jankapunkt** [comment]
Thank you, good question. I rather did this to have something that initially worked so it is definitely open to improvements.

I assume you refer to the following part of the table definition [in line 245](https://github.com/jankapunkt/latexcv/blob/master/modern/main.tex#L245): `p{10.8cm}`

I basically use this to format the table columns width rather than it's content layout so a fix may require a custom column design.

There is already an approach to a custom column at the third parameter: `x{3.9cm}`

Which is defined in [line 114](https://github.com/jankapunkt/latexcv/blob/master/modern/main.tex#L114) as

```
\newcolumntype{x}[1]{%
>{\raggedleft\hspace{0pt}}p{#1}}%
```

I mainly used the [Wikibooks article](https://en.wikibooks.org/wiki/LaTeX/Tables#Column_specification_using_%3E%7B%5Ccmd%7D_and_%3C%7B%5Ccmd%7D) to create this.

Maybe there is a custom column solution for the second parameter that can handle overflow, at least there is an [example in the Wikibooks article](https://en.wikibooks.org/wiki/LaTeX/Tables#Manually_broken_paragraphs_in_table_cells) that uses a `\parbox` to break parapgraphs.

I will flag this as open for PRs you (or anyone else) can try on that. Should also be a good issue for those who want to try their first pull request.

**Comment by slevin18** [comment]
Hi @jankapunkt , I think I have the same problem. I would like to show also the other params , not only event name

        %  param 3:  event name
	% param 4:	institution (where did you work / study)
	% param 5:	what was your position

So I want a Big block that can contains the other informations  without overflowing on the right (this is another problem: now, If I write an event name too long, the text goes in overflow).

I hope that you solve my problem. You did a great job!

**Comment by jankapunkt** [comment]
@sebastian-raubach @slevin18 any interesting improvements on your sides?

**Comment by jankapunkt** [comment]
@sebastian-raubach @slevin18  this is now implemented in imfographics 2, see #46

I will close this. feel free to reopen if this not a valid solution
